#!/bin/bash

# Script to populate Brain Dump database with Kids Meal Luxury Redesign tickets
# Generated by Claude Code - Spec Breakdown Agent

DB_PATH="/Users/salman.rana/Library/Application Support/brain-dump/brain-dump.db"
PROJECT_ID="kids-meal-$(date +%s)"
PROJECT_PATH="/Users/salman.rana/code/personal-projects/kids-meal"

echo "Populating Brain Dump with Kids Meal Luxury Redesign project..."
echo "Project ID: $PROJECT_ID"

# Create the project
sqlite3 "$DB_PATH" "INSERT INTO projects (id, name, path, color, working_method) VALUES ('$PROJECT_ID', 'kids meal', '$PROJECT_PATH', '#D4AF37', 'auto');"

echo "✓ Created project: kids meal"

# Function to create epic
create_epic() {
  local epic_id="$1"
  local title="$2"
  local description="$3"
  local color="${4:-#D4AF37}"

  sqlite3 "$DB_PATH" "INSERT INTO epics (id, title, description, project_id, color) VALUES ('$epic_id', '$title', '$description', '$PROJECT_ID', '$color');"
  echo "✓ Created epic: $title"
}

# Function to create ticket
create_ticket() {
  local ticket_id="$1"
  local epic_id="$2"
  local title="$3"
  local priority="$4"
  local position="$5"
  local tags="$6"
  local description="$7"

  # Escape single quotes in description for SQL
  description=$(echo "$description" | sed "s/'/''/g")

  sqlite3 "$DB_PATH" "INSERT INTO tickets (id, title, description, status, priority, position, project_id, epic_id, tags) VALUES ('$ticket_id', '$title', '$description', 'backlog', '$priority', $position, '$PROJECT_ID', '$epic_id', '$tags');"
}

# Create Epic 1: Design System Foundation
create_epic "epic-1-$PROJECT_ID" "Design System Foundation" "Establish the luxury design system including color palette, typography, spacing, and CSS variables" "#FF6B6B"

create_ticket "ticket-1-1-$PROJECT_ID" "epic-1-$PROJECT_ID" "Finalize and document luxury color palette" "high" 1.0 "design,setup,css,accessibility" "Create color palette with 6 colors. Define CSS variables in src/styles/colors.css. Test WCAG AA contrast ratios."

create_ticket "ticket-1-2-$PROJECT_ID" "epic-1-$PROJECT_ID" "Select and implement premium fonts" "high" 2.0 "design,typography,fonts" "Choose serif font for headlines (Playfair Display) and sans-serif for body (Inter). Load via Google Fonts. Define typography hierarchy."

create_ticket "ticket-1-3-$PROJECT_ID" "epic-1-$PROJECT_ID" "Create CSS design tokens and variables" "high" 3.0 "design,css,tokens" "Create src/styles/tokens.css with spacing scale (8px base), shadows, border radius, and transitions."

create_ticket "ticket-1-4-$PROJECT_ID" "epic-1-$PROJECT_ID" "Document design system guidelines" "medium" 4.0 "documentation,design" "Create docs/DESIGN_SYSTEM.md documenting color palette, typography, spacing, and component usage."

echo "✓ Created Epic 1: Design System Foundation (4 tickets)"

# Create Epic 2: Component Library Refinement
create_epic "epic-2-$PROJECT_ID" "Component Library Refinement" "Redesign core UI components to match luxury aesthetic" "#4ECDC4"

create_ticket "ticket-2-1-$PROJECT_ID" "epic-2-$PROJECT_ID" "Redesign button component with luxury styling" "high" 5.0 "component,design,button" "Create Button component with primary, secondary, tertiary variants. Use design tokens. Implement hover, active, disabled states."

create_ticket "ticket-2-2-$PROJECT_ID" "epic-2-$PROJECT_ID" "Redesign card component" "high" 6.0 "component,design,card" "Create Card component for recipe display. Include image area, content area, optional actions. Use 12px border radius and subtle shadow."

create_ticket "ticket-2-3-$PROJECT_ID" "epic-2-$PROJECT_ID" "Redesign navigation component" "high" 7.0 "component,design,navigation" "Update Navigation component with elegant desktop top nav and refined mobile bottom nav. Clear active states."

create_ticket "ticket-2-4-$PROJECT_ID" "epic-2-$PROJECT_ID" "Create luxury input and form components" "medium" 8.0 "component,design,forms" "Create FormInput component with labels, focus states, error states. Ensure accessibility."

create_ticket "ticket-2-5-$PROJECT_ID" "epic-2-$PROJECT_ID" "Redesign tabs component" "medium" 9.0 "component,design,tabs,accessibility" "Create Tabs component with underline-style design. Implement keyboard navigation and ARIA support."

echo "✓ Created Epic 2: Component Library Refinement (5 tickets)"

# Create Epic 3: Discover Page Redesign
create_epic "epic-3-$PROJECT_ID" "Discover Page Redesign" "Transform swipe discovery interface with elegant card design" "#95E1D3"

create_ticket "ticket-3-1-$PROJECT_ID" "epic-3-$PROJECT_ID" "Redesign swipe card with elegant frame and image treatment" "high" 10.0 "design,discover,card,responsive" "Update DiscoverPage.jsx swipe cards. Apply elegant frame, 12px border radius, proper image sizing (object-fit: cover)."

create_ticket "ticket-3-2-$PROJECT_ID" "epic-3-$PROJECT_ID" "Refine recipe metadata display" "high" 11.0 "design,typography,discover" "Apply serif font to recipe titles, display prep time and cuisine with proper hierarchy. Ensure WCAG AA contrast."

create_ticket "ticket-3-3-$PROJECT_ID" "epic-3-$PROJECT_ID" "Enhance swipe animations" "medium" 12.0 "animation,discover,performance" "Refine swipe animations for smooth 60fps performance. Use GPU-accelerated properties (transform, opacity)."

create_ticket "ticket-3-4-$PROJECT_ID" "epic-3-$PROJECT_ID" "Optimize discover page responsive layout" "medium" 13.0 "responsive,discover,mobile,tablet" "Test layouts: Mobile (<768px) 70vh card, Tablet (768-1024px) medium, Desktop (>1024px) 400px max."

create_ticket "ticket-3-5-$PROJECT_ID" "epic-3-$PROJECT_ID" "Add subtle loading and empty states to discover" "low" 14.0 "ux,discover,loading,empty-state" "Design loading skeleton card and empty state message. Match luxury aesthetic."

echo "✓ Created Epic 3: Discover Page Redesign (5 tickets)"

# Create Epic 4: Liked Recipes Redesign
create_epic "epic-4-$PROJECT_ID" "Liked Recipes Redesign" "Redesign recipe collection grid with image-forward layout" "#F38181"

create_ticket "ticket-4-1-$PROJECT_ID" "epic-4-$PROJECT_ID" "Implement grid layout with luxury spacing" "high" 15.0 "layout,liked,responsive,grid" "Create responsive grid in LikedPage.jsx: Mobile 2-col, Tablet 3-col, Desktop 4-col. Use CSS Grid with proper gaps."

create_ticket "ticket-4-2-$PROJECT_ID" "epic-4-$PROJECT_ID" "Redesign recipe grid cards" "high" 16.0 "design,card,liked" "Use Card component for grid items. Image-forward design with consistent aspect ratio. Add hover elevation."

create_ticket "ticket-4-3-$PROJECT_ID" "epic-4-$PROJECT_ID" "Add hover states and interactions" "medium" 17.0 "interaction,liked,animation" "Implement subtle card elevation on hover, show action buttons. Smooth transitions using design tokens."

create_ticket "ticket-4-4-$PROJECT_ID" "epic-4-$PROJECT_ID" "Optimize liked page mobile experience" "medium" 18.0 "responsive,liked,mobile" "Test 2-column grid on mobile. Ensure 44x44px touch targets, no horizontal scrolling."

create_ticket "ticket-4-5-$PROJECT_ID" "epic-4-$PROJECT_ID" "Add empty state and loading states" "low" 19.0 "ux,liked,loading,empty-state" "Create empty state message and loading skeleton matching grid layout."

echo "✓ Created Epic 4: Liked Recipes Redesign (5 tickets)"

# Create Epic 5: Weekly Planner Redesign
create_epic "epic-5-$PROJECT_ID" "Weekly Planner Redesign" "Enhance kanban board with elegant columns and refined spacing" "#AA96DA"

create_ticket "ticket-5-1-$PROJECT_ID" "epic-5-$PROJECT_ID" "Redesign kanban column headers with premium styling" "high" 20.0 "design,layout,planner" "Style day labels with serif font, subtle background, clear hierarchy. Responsive on all breakpoints."

create_ticket "ticket-5-2-$PROJECT_ID" "epic-5-$PROJECT_ID" "Refine meal cards in planner" "high" 21.0 "design,card,planner" "Use Card component for meal cards. Display recipe title, time, actions. Ensure draggable without clutter."

create_ticket "ticket-5-3-$PROJECT_ID" "epic-5-$PROJECT_ID" "Improve desktop kanban layout spacing" "high" 22.0 "layout,planner,desktop" "Show full week without scroll on desktop. 24px gap between columns. Max-width 1200px container."

create_ticket "ticket-5-4-$PROJECT_ID" "epic-5-$PROJECT_ID" "Implement mobile planner layout" "high" 23.0 "responsive,layout,planner,mobile" "Implement horizontal scroll or day-by-day view for mobile. Day picker prominent. Cards readable and draggable."

create_ticket "ticket-5-5-$PROJECT_ID" "epic-5-$PROJECT_ID" "Enhance drag and drop animations" "medium" 24.0 "animation,planner" "Smooth drag animation, subtle drop zone highlight, smooth card placement. 60fps performance."

create_ticket "ticket-5-6-$PROJECT_ID" "epic-5-$PROJECT_ID" "Add visual feedback for planner interactions" "medium" 25.0 "ux,animation,planner" "Hover state on droppable areas, visual feedback during drag, success feedback after drop."

echo "✓ Created Epic 5: Weekly Planner Redesign (6 tickets)"

# Create Epic 6: Recipe Detail Redesign
create_epic "epic-6-$PROJECT_ID" "Recipe Detail Redesign" "Transform recipe detail page with premium image treatment" "#FCBAD3"

create_ticket "ticket-6-1-$PROJECT_ID" "epic-6-$PROJECT_ID" "Redesign recipe detail header with premium image treatment" "high" 26.0 "design,images,detail" "Large image display (full-width or centered), elegant frame, refined title placement. Preserve image quality."

create_ticket "ticket-6-2-$PROJECT_ID" "epic-6-$PROJECT_ID" "Implement sophisticated tab design" "high" 27.0 "design,tabs,detail" "Use Tabs component from Epic 2. Underline-style tabs for ingredients and instructions."

create_ticket "ticket-6-3-$PROJECT_ID" "epic-6-$PROJECT_ID" "Refine ingredients and steps typography" "high" 28.0 "typography,detail" "Generous padding (24-32px), 60-80 char line length, clear hierarchy. Ingredient list bulleted, steps numbered."

create_ticket "ticket-6-4-$PROJECT_ID" "epic-6-$PROJECT_ID" "Add elegant action buttons and navigation" "medium" 29.0 "design,navigation,detail" "Back button, share button, add-to-plan button. Use Button component. 44x44px touch targets."

create_ticket "ticket-6-5-$PROJECT_ID" "epic-6-$PROJECT_ID" "Optimize recipe detail for mobile" "medium" 30.0 "responsive,detail,mobile" "Full-width image on mobile, content stacks nicely, tabs work on small screens."

create_ticket "ticket-6-6-$PROJECT_ID" "epic-6-$PROJECT_ID" "Add loading and error states to detail page" "low" 31.0 "ux,detail,loading,error" "Loading skeleton for image and content. Error message if recipe fails to load."

echo "✓ Created Epic 6: Recipe Detail Redesign (6 tickets)"

# Create Epic 7: Grocery List Redesign
create_epic "epic-7-$PROJECT_ID" "Grocery List Redesign" "Redesign shopping list with categorized layout and elegant styling" "#A8E6CF"

create_ticket "ticket-7-1-$PROJECT_ID" "epic-7-$PROJECT_ID" "Implement categorized list layout with icons" "high" 32.0 "layout,design,grocery" "Categories (Produce, Meat, Dairy, etc.) with icons. Subtle dividers. Generous padding using tokens."

create_ticket "ticket-7-2-$PROJECT_ID" "epic-7-$PROJECT_ID" "Refine list typography and readability" "high" 33.0 "typography,grocery" "Readable ingredient names, clear quantities, proper line spacing, high contrast."

create_ticket "ticket-7-3-$PROJECT_ID" "epic-7-$PROJECT_ID" "Enhance copy-to-clipboard feedback" "medium" 34.0 "ux,grocery" "Refined copy button using Button component. Success message with animation. Button text changes to 'Copied!'."

create_ticket "ticket-7-4-$PROJECT_ID" "epic-7-$PROJECT_ID" "Implement print-friendly styling" "medium" 35.0 "print,grocery" "Print media query. Layout optimized for paper. Hide navigation. Readable when printed."

create_ticket "ticket-7-5-$PROJECT_ID" "epic-7-$PROJECT_ID" "Add grocery list empty and loading states" "low" 36.0 "ux,grocery,loading,empty-state" "Empty state: 'Plan meals to generate list'. Loading skeleton showing categories."

echo "✓ Created Epic 7: Grocery List Redesign (5 tickets)"

# Create Epic 8: Responsive & Mobile Optimization
create_epic "epic-8-$PROJECT_ID" "Responsive & Mobile Optimization" "Ensure responsive design works elegantly across all breakpoints" "#FFD3B6"

create_ticket "ticket-8-1-$PROJECT_ID" "epic-8-$PROJECT_ID" "Test and refine mobile breakpoint layouts (<768px)" "high" 37.0 "responsive,testing,qa,mobile" "Test all pages on mobile. Navigation functional, text readable, 44x44px touch targets, no horizontal scroll."

create_ticket "ticket-8-2-$PROJECT_ID" "epic-8-$PROJECT_ID" "Optimize tablet layouts (768-1024px)" "medium" 38.0 "responsive,testing,qa,tablet" "Test all pages at 768-1024px. Intermediate grid layouts, refined navigation, proper spacing."

create_ticket "ticket-8-3-$PROJECT_ID" "epic-8-$PROJECT_ID" "Refine desktop experience (>1024px)" "medium" 39.0 "responsive,testing,qa,desktop" "Desktop layouts maximize screen real estate. Max-width containers, generous spacing, multi-column layouts."

create_ticket "ticket-8-4-$PROJECT_ID" "epic-8-$PROJECT_ID" "Ensure touch-friendly interactions" "high" 40.0 "responsive,mobile,ux,touch" "All buttons 44x44px minimum. Adequate spacing between touch targets. Test on real devices."

create_ticket "ticket-8-5-$PROJECT_ID" "epic-8-$PROJECT_ID" "Test responsive images and performance" "medium" 41.0 "responsive,performance,qa,images" "Images load correctly at all breakpoints. Lazy loading working. No layout shift."

echo "✓ Created Epic 8: Responsive & Mobile Optimization (5 tickets)"

# Create Epic 9: Animations & Micro-interactions
create_epic "epic-9-$PROJECT_ID" "Animations & Micro-interactions" "Add smooth page transitions, hover states, and refined feedback" "#FFAAA5"

create_ticket "ticket-9-1-$PROJECT_ID" "epic-9-$PROJECT_ID" "Add page transition animations" "medium" 42.0 "animation,ux" "Smooth transitions between routes. Fade or slide effects. 300-500ms timing. 60fps performance."

create_ticket "ticket-9-2-$PROJECT_ID" "epic-9-$PROJECT_ID" "Implement refined hover states" "medium" 43.0 "animation,ux,hover" "Buttons: subtle color/elevation change. Cards: soft elevation. Links: underline/color change. Use --transition-base."

create_ticket "ticket-9-3-$PROJECT_ID" "epic-9-$PROJECT_ID" "Design loading state animations" "medium" 44.0 "animation,ux,loading" "Skeleton screens matching content layout. Subtle pulsing or shimmer. Premium appearance."

create_ticket "ticket-9-4-$PROJECT_ID" "epic-9-$PROJECT_ID" "Implement success and error feedback animations" "medium" 45.0 "animation,ux,feedback" "Success messages: subtle enter/exit animation. Error alerts: clear but not jarring. Use design tokens."

create_ticket "ticket-9-5-$PROJECT_ID" "epic-9-$PROJECT_ID" "Polish form interaction animations" "low" 46.0 "animation,ux,forms" "Input focus: subtle color change. Floating labels: smooth animation. Validation feedback: smooth appearance."

echo "✓ Created Epic 9: Animations & Micro-interactions (5 tickets)"

# Create Epic 10: Polish & Quality Assurance
create_epic "epic-10-$PROJECT_ID" "Polish & Quality Assurance" "Visual QA, accessibility audit, performance optimization" "#B4A7D6"

create_ticket "ticket-10-1-$PROJECT_ID" "epic-10-$PROJECT_ID" "Conduct visual QA across all pages" "high" 47.0 "qa,testing,visual" "Review all pages for design consistency, spacing, alignment, typography, colors. Document screenshots."

create_ticket "ticket-10-2-$PROJECT_ID" "epic-10-$PROJECT_ID" "Perform accessibility audit (WCAG 2.1 AA)" "high" 48.0 "qa,accessibility,wcag" "Verify contrast ratios (4.5:1), keyboard navigation, screen reader testing, focus states, ARIA labels. Run Lighthouse."

create_ticket "ticket-10-3-$PROJECT_ID" "epic-10-$PROJECT_ID" "Optimize performance metrics" "high" 49.0 "qa,performance,optimization" "60fps animations, page load < 3s, FCP < 1.5s. Minify CSS, optimize images, CLS < 0.1. Lighthouse > 90."

create_ticket "ticket-10-4-$PROJECT_ID" "epic-10-$PROJECT_ID" "Test cross-browser compatibility" "medium" 50.0 "qa,testing,cross-browser" "Test on Chrome, Firefox, Safari, Edge, mobile browsers. Ensure consistent rendering. No critical bugs."

create_ticket "ticket-10-5-$PROJECT_ID" "epic-10-$PROJECT_ID" "Create final design documentation" "medium" 51.0 "documentation,design" "Document design decisions in docs/DESIGN_FINAL.md. Include screenshots, color palette, typography, spacing, animations."

create_ticket "ticket-10-6-$PROJECT_ID" "epic-10-$PROJECT_ID" "Get stakeholder approval on redesign" "high" 52.0 "qa,stakeholder,approval" "Present redesign to team, collect feedback, make refinements, obtain final sign-off for production."

echo "✓ Created Epic 10: Polish & Quality Assurance (6 tickets)"

echo ""
echo "========================================="
echo "✅ Successfully populated Brain Dump!"
echo "========================================="
echo "Project: kids meal"
echo "Project ID: $PROJECT_ID"
echo "Path: $PROJECT_PATH"
echo "Epics: 10"
echo "Tickets: 52"
echo ""
echo "Priority breakdown:"
echo "  HIGH: 26 tickets (50%)"
echo "  MEDIUM: 20 tickets (38%)"
echo "  LOW: 6 tickets (12%)"
echo ""
echo "Open Brain Dump to view your project!"
echo ""
